# Generated by Django 2.2.4 on 2019-08-04 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_title', models.CharField(max_length=250)),
                ('synopsis', models.TextField(blank=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800, "Movies didn't exist back then."), django.core.validators.MaxValueValidator(2050, "You're way in the future.")])),
                ('runtime_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Movies last at least a minute.')])),
                ('cover_art', models.ImageField(blank=True, upload_to='')),
                ('genres', models.ManyToManyField(blank=True, to='catalogue.Genre')),
            ],
        ),
    ]
